/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectsRouteImport } from './routes/architects'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsRoute = ArchitectsRouteImport.update({
  id: '/architects',
  path: '/architects',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/email': typeof EmailRoute
  '/estimator': typeof EstimatorRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/email': typeof EmailRoute
  '/estimator': typeof EstimatorRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/email': typeof EmailRoute
  '/estimator': typeof EstimatorRoute
  '/planner': typeof PlannerRoute
  '/research': typeof ResearchRoute
  '/responsible-ai': typeof ResponsibleAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architects'
    | '/email'
    | '/estimator'
    | '/planner'
    | '/research'
    | '/responsible-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architects'
    | '/email'
    | '/estimator'
    | '/planner'
    | '/research'
    | '/responsible-ai'
  id:
    | '__root__'
    | '/'
    | '/architects'
    | '/email'
    | '/estimator'
    | '/planner'
    | '/research'
    | '/responsible-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectsRoute: typeof ArchitectsRoute
  EmailRoute: typeof EmailRoute
  EstimatorRoute: typeof EstimatorRoute
  PlannerRoute: typeof PlannerRoute
  ResearchRoute: typeof ResearchRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects': {
      id: '/architects'
      path: '/architects'
      fullPath: '/architects'
      preLoaderRoute: typeof ArchitectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectsRoute: ArchitectsRoute,
  EmailRoute: EmailRoute,
  EstimatorRoute: EstimatorRoute,
  PlannerRoute: PlannerRoute,
  ResearchRoute: ResearchRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
